### ISSUE TITLE
请问为什么要移除deepL的接口啊

### ISSUE THREAD

**Issue by sadowrm** [speauty/man.subtitle.translate#11]
刚好需要这个，泪流满面

**Comment by speauty** [comment]
我之前对接的那个DeepL是扒拉得来的，，，限制的太严重完全没法用。。。正式的那个需要什么visa卡那些，我这边没有。。。如果有朋友直接提供给我DeepL的密钥什么之类的，我倒是可以操作

**Comment by fqscfqj** [comment]
> 我之前对接的那个DeepL是扒拉得来的，，，限制的太严重完全没法用。。。 正式的那个需要什么visa卡那些，我这边没有。。。 如果有朋友直接提供给我DeepL的密钥什么之类的，我倒是可以操作

发了两个key到邮箱

**Comment by speauty** [comment]
已接入，接口响应比较慢，可能本地网络原因。

**Comment by kedyao** [comment]
这个不限制的api能否接入 https://github.com/OwO-Network/DeepLX/

**Comment by kedyao** [comment]
怎么最新的3.4.2下载里面没有 deeplx的接口

**Comment by speauty** [comment]
> 怎么最新的3.4.2下载里面没有 deeplx的接口

我稍后检查一下

**Comment by speauty** [comment]
> 怎么最新的3.4.2下载里面没有 deeplx的接口

点击 文件 => 下载新版 即可，当前Release暂没有发布最新版本的，我稍后更新一下。
