### ISSUE TITLE
一个错误反馈+一个建议

### ISSUE THREAD

**Issue by GuiyuOneiros** [speauty/man.subtitle.translate#2]
1. 使用腾讯云翻译时显示“当前每秒请求‘6’次，超过每秒频率上限‘5’ ”
2. 对不同服务商增加后缀区分

**Comment by speauty** [comment]
ok，收到。刚简单复现了一下，确实QPS限制挺难受的，我这边马上处理下。那个服务商增加后缀区分，我这里是补充了翻译引擎回显，可以明确当前使用的引擎。不知道是不是你这里提到的增加后缀区分（估计刚开始我可能没回显引擎）
![image](https://user-images.githubusercontent.com/28774023/234156779-65ccd1b7-828e-4b63-9b97-0e4b153aa45e.png)

**Comment by speauty** [comment]
那个错误反馈，是软件这边请求腾讯翻译过快导致的。现已修正，做了限制，不过，可能翻译就有点慢哦。

**Comment by GuiyuOneiros** [comment]
> 那个错误反馈，是软件这边请求腾讯翻译过快导致的。现已修正，做了限制，不过，可能翻译就有点慢哦。

感谢。此外百度普通版和高级版的qps有所不同，不过能用这服务的应该都会切高级版所以影响不大

增加后缀区分指生成字幕文件的文件名末尾添加一个后缀例如bd、cy等进行区别，有些不同的运营商生成的字幕文件名相同。tern的开发者是在生成字幕的文件名开头添加服务商的英文名进行区分。还有可以添加一个字符统计功能（不过这俩功能有没有也不影响使用）

最后新版本2.9.4下载后会被wd误报Trojan:Win32/Wacatac.H!ml ，目前我的三个设备中只有win10 ltsc系统下的wd不会报毒，设置信任倒不是很麻烦，就是下载后双击直接被wd拖去隔离区有点麻烦……不过wd的误报也不太好定位，我也就稍微提一下

**Comment by speauty** [comment]
关于百度不同版本的QPS暂未适配，目前仅对齐标准版，后面可能会开放QPS配置（今晚又调整了下QPS限制策略，似乎还存在一定问题，不过影响不大，不翻译大字幕文件基本可以避过这个限制）。后缀那个，我估计要加，还要补充个标记，防止被重复翻译（选择目录可能会存在，很烦）；字符统计那个，之前想过，但是没做，具体什么原因忘了。最后误报那个，可能是我压缩的原因，之前遇到过，这个倒是问题不大。


最后，感谢朋友的支持和反馈，我会努力优化完善这个工具的。
