### ISSUE TITLE
百度翻译 api 无法使用

### ISSUE THREAD

**Issue by zx3777** [speauty/man.subtitle.translate#3]
投递完以后就不动了，然后 cpu占用一直 20%-30%，关闭才好。彩云是可用的。

api测试过是对的。

**Comment by zx3777** [comment]
2.9.2 可用， 2.9.4不行。另外希望添加拖放添加字幕文件的功能，现在添加单个文件太麻烦了。还有希望可以选择字幕不添加标点符号。

**Comment by speauty** [comment]
我这边先处理下百度翻译服务无法使用的问题。关于那个添加单个文件太麻烦了，可以采用选择目录的方式，不过要提前需要翻译的字幕放进去（不过这里有个小问题，如果二次选择当前目录，会翻译已翻译的字幕哦）。另外，关于标点符号那个，其实我也挺烦的，有打算做个去除尾字符的想法（可能需要自行配置清除字符集合，毕竟语种那些问题，不大确定，句号是否就只有。和.两种）。
