### ISSUE TITLE
请问增量翻译和全量翻译是什么意思啊？

### ISSUE THREAD

**Issue by soloycf** [speauty/man.subtitle.translate#4]
增量就是一行一行翻译吗？
全量的意思是一次全文翻译，有上下文背景吗？

**Comment by speauty** [comment]
不是的，传统机器翻译，不存在上下文这个概念。全量就是全部翻译，包括可能已经翻译的行；反之，就是增量模式，简单点说，就是直接过滤已翻译的行，只处理未翻译的。毕竟，有时，可能会存在部分行已翻译的情况。
