### ISSUE TITLE
腾讯云设置问题

### ISSUE THREAD

**Issue by GuiyuOneiros** [speauty/man.subtitle.translate#7]
3.4.2版本设置腾讯云密钥并重启后腾讯云的设置仍为空。打开cfg.yml发现tencent_cloud_mt下为初始配置，而tencent_mt里是输入的密钥。将tencent_mt里的内容复制到tencent_cloud_mt后重新打开应用，即可正确显示腾讯云

**Comment by speauty** [comment]
在菜单中下载新版就可以咯，感谢朋友反馈~
